### ISSUE TITLE
how can I filter an area?

### ISSUE THREAD

**Issue by love010608** [myspace-nu/jquery.fancyTable#10]
.If data-sortas="numeric" ,how can I filter an area?Exaple 15,25,8,63,7,9,13.I want chose the number>10,the result 15,25,63,13.

**Comment by myspace-nu** [comment]
There is no such functionality today and I don't think it will be added. The focus of the plugin is to be lightweight and easy to setup. Adding parsing for this would mean a proportionately large addition of code for this edge case. The next logical step would be to add intervals (13-27, -5..15) or sequences (1,5,78). I might add something like custom search functions to not bloat the code, but then you will have to write your own comparison function.
