### ISSUE TITLE
Case insensitive sorting please

### ISSUE THREAD

**Issue by mjsambol** [myspace-nu/jquery.fancyTable#12]
Hi, thanks for this helpful and easy to use component!

The sort order is sensitive to case, but this is not always desirable. Can you please add support for case insensitive sorting? This could be with another data-sortas option on the th element, or alternatively and more powerfully, with an additional attribute on each td element that would be used for its sort value. For example:

`<td data-sortas="all lowercase">Mixed Case</td>`

which would also enable

`<td data-sortas="3">Three</td>`

**Comment by myspace-nu** [comment]
Great idea! Thanks for the feedback.
I have added the \<th> attribute data-sortas="case-insensitive" and also the \<td> attribute  data-sortvalue="`<value>`" to not mix them up.
