### ISSUE TITLE
Sorting with filesizes

### ISSUE THREAD

**Issue by SAGOnly** [myspace-nu/jquery.fancyTable#16]
Hi,
be able integrate data sorting on the file size according to said KB, MB, GB, TB into the table, such as this plugin?
https://github.com/DataTables/Plugins/blob/master/sorting/file-size.js
or possibly
https://mottie.github.io/tablesorter/docs/example-parsers-metric.html
Thank you

**Comment by myspace-nu** [comment]
Hi,
I don't think I want to go down that rabbit hole :) After file sizes the next thing would be comparing other metric units; meters, kilograms. Then why not compare imperial units as well; inches, miles, gallons. However, adding the possibility to use a custom sort function would solve this. Then you could customize it to fit whatever application it's used for. I could add that to the next release.

**Comment by myspace-nu** [comment]
Custom sort function has now been added to the current release.

**Comment by SAGOnly** [comment]
Hello,
Thank you for adding this feature. I tried to try it, but he still doesn't work. When I want to sort her in an HTML table by file size and according to units (KB, MB, GB, TB), I must somehow extra editable files fancytable.js and fancytable.min.js?
In the picture you can see sorting from the largest to the smallest file and vice versa from the smallest to the largest file, but it can only sort it by numbers, the units does not recognize.
![sort2](https://user-images.githubusercontent.com/90079674/132499048-5ff6256f-8344-499d-bb5f-5ec48a25175e.png)
![sort1](https://user-images.githubusercontent.com/90079674/132499053-04066c66-5e4d-4750-b3fb-5e72f4aef986.png)

**Comment by myspace-nu** [comment]
You have to write your own sort function that suits your needs. Here's a quick-and-dirty example: https://codepen.io/myspace-nu/pen/mdwRpjO

**Comment by myspace-nu** [comment]
Thank you, you're welcome :)
