### ISSUE TITLE
Accessibility: aria-sort attributes

### ISSUE THREAD

**Issue by adamjohnson** [myspace-nu/jquery.fancyTable#18]
For tables that have sorting enabled, they should:

  1. Use an accessible control to enable sorting (like the `<button>` element) with an accessible name, `aria-labelledby` or `aria-label` to denote what the control does.
     * FancyTable does this via the `<a>` tag and puts the content of the `<th>` in the `<a>` tag as the accessible name. That works ✔️. 
  2. Apply `aria-sort` attributes to table headers (`<th>`) that change based off of the state of the table.

For some background on aria-sort, see [Sortable Table Columns](https://adrianroselli.com/2021/04/sortable-table-columns.html) by Adrian Roselli. The [Basics](https://adrianroselli.com/2021/04/sortable-table-columns.html#Basics) and [Sort Arrows](https://adrianroselli.com/2021/04/sortable-table-columns.html#Arrows) sections of that article are especially relevant.

**Comment by myspace-nu** [comment]
Using the content of the `a`-element and just add "Sort by" in front should suffice I guess. I.e. "Sort by department".

**Comment by myspace-nu** [comment]
Fix added to e294ee1d2f5e605d21ec2986dfc0998aea79a168

**Comment by adamjohnson** [comment]
Adding `Sort by XYZ` to the beginning announces `Sort by XYZ` for every cell when navigating via VoiceOver via CTRL + OPT + Arrow keys. It works, but it definitely is verbose. Tricky!

Looking at Adrian's post, it looks like he outputs `Sorted Down` / `Sorted Up` to a live region thats `visually-hidden`. This keeps it from being announced by the screen reader when navigating the table. Here's [his demo](https://codepen.io/aardrian/full/NJQNQV).

So, maybe instead of appending "Sort by" to the table header, it could be added to a visually-hidden aria-live region? That might be the most ideal. Otherwise, what you have will work.

____________________________

Also, it looks like, after clicking to sort a column, the `<th>` elements surrounding the search inputs get the `aria-sort` attributes added to them as well. They likely don't need to be on those table header elements.

**Comment by myspace-nu** [comment]
> Also, it looks like, after clicking to sort a column, the `<th>` elements surrounding the search inputs get the `aria-sort` attributes added to them as well. They likely don't need to be on those table header elements.

I will remove the `aria-sort` attribute instead of setting the value to "none" in the next release.
