### ISSUE TITLE
Write search parameter to url param

### ISSUE THREAD

**Issue by Moustachauve** [myspace-nu/jquery.fancyTable#27]
Hi! 

It would be nice to have an option to read/write the search param to the page url with something like "window.history.replaceState" so that search can be maintained when page is refreshed

**Comment by myspace-nu** [comment]
Hmm, that might be a nice feature. Would need to add some comprehensive configuration options for that so it doesn't interfere with other functions on the site that might rely on the URL or querystring. Could possibly be better to use sessionStorage for it. I'll add it to the backlog for possible future features.

**Comment by Moustachauve** [comment]
Reason I suggested url instead of sessionStorage is so you could easily share it to someone else to get to the same point. Thank you for considering this, I really like using fancyTables :)
