### ISSUE TITLE
Sorting using `data-sortvalue` is broken if 0 values are present

### ISSUE THREAD

**Issue by VPetukhov** [myspace-nu/jquery.fancyTable#28]
Current sorting procedure extracts `data-sortvalue` using [the following code](https://github.com/myspace-nu/jquery.fancyTable/blob/master/src/fancyTable.js#L139):
```js
var cmpa = $(elma).data("sortvalue") ? $(elma).data("sortvalue") : elma.html();
```

So, in case `$(elma).data("sortvalue") == 0`, this code assumes that `data-sortvalue` is not set and uses the value instead. For example, if my table has a row `<td data-sortvalue="0">Your number is 0!</td>`, the sorting will not work correctly. I'm new in JavaScript, but I tried suggestions from [here](https://stackoverflow.com/questions/12161132/is-there-a-way-that-i-can-check-if-a-data-attribute-exists), and the following one works well:

```js
var cmpa = $(elma).is("[data-sortvalue]") ? $(elma).data("sortvalue") : elma.html();
```

**Comment by myspace-nu** [comment]
Thanks for the feedback! A fix has been added to a2a2536808c05ec4c4eeed20e71b6bcd7110ae91
