### ISSUE TITLE
Error when inputting invalid characters

### ISSUE THREAD

**Issue by MaledongGit** [myspace-nu/jquery.fancyTable#32]
Hi:

It seems if I input some chars such as "(", ")", "."... It will report me errors by F12 (of course I know the reason that they belong to the key words of Regex itself). However I don't think it right, and it should allow us to input any characters including these special characters.

**Comment by myspace-nu** [comment]
Right. First I thought I'd just escape the input. But that might break functionality since some use cases might rely on the fact that it's a regular expression. So I opted for just throw it in a try-catch block. Fixed version 706d40c6821002d721b84ae23d641ad780da8687
