### ISSUE TITLE
Consecutive sorts mess up the order

### ISSUE THREAD

**Issue by Rodnan** [myspace-nu/jquery.fancyTable#33]
I have a table with 396 elements, and two of the columns contains a random string witch starts with a number. Every row has a data-sortvalue, which is set to the given number of the start of the random string. The data-sortas is set to numeric, so everything should be fine. But if I sort the first column, then the second, then the first again, then the sort won't be correct.

**Comment by myspace-nu** [comment]
I'm sorry, but I cannot replicate the issue. I have added an example to the Codepen demo https://codepen.io/myspace-nu/full/ZVEKyR (last table). And it works fine. I have padded the numeric data-sortvalue with 0 ("010" for 10) to make sure that works as well.

**Comment by Rodnan** [comment]
Maybe i wasn't specific about the details, i am sorry. I recreated the issue here: https://codepen.io/rodnan/full/LYdOmZO . If you sort by the D row, then the DN row, the sort won't be correct.

**Comment by myspace-nu** [comment]
From what I can tell it's working as intended. I think you have misinterpreted what the numeric sort does. Normaly (if nothing else is specified) data will be sorted alphabetically, e.i. 1,10,100,2,3,4,a,b,c... If you set data-sortas to "numeric" numbers will be sorted as 1,2,3,4,10,100 ... It will not evaluate data like "50-20" and sort it as 30.

**Comment by Rodnan** [comment]
I get it, this is why i have the first value set as the sort-value.

So again. There are those strings, these represent dimensions. I have to sort them, so I chose the approach where I sort by the first appearing number. I put that number in the "sort-value", and it appears that that part is correct. When I sort by them (the way I wrote above) however it does not sort correctly.

The problem appears to be with the sort-value logic.

**Comment by myspace-nu** [comment]
I follow the steps in your example, and I still can't see where it's sorting incorrectly. I sort by column D, then DN and it appears sorted to me. 15, 20, 25, 32, 40 and so on.

**Comment by myspace-nu** [comment]
Or do you mean that rows of equal sort priority (i.e. same numeric value) should be sorted according to the previously selected columns order (D in your example). This behavious is what you expect from Excel for example. But this is not intended behaviour for the script. It only sorts by 1 column.

**Comment by myspace-nu** [comment]
I've had a look at this and the behaviour described above could be implemented pretty easily plus it should not break functionality since the sort order of equal column values is undefined today.

**Comment by myspace-nu** [comment]
Issue closed due to inactivity and missing information.
