### ISSUE TITLE
<th data-sortas="numeric"> not working

### ISSUE THREAD

**Issue by RZSysadmin** [myspace-nu/jquery.fancyTable#36]
When I add this flag I still get numbers sorted as 
1, 13, 14, 16, 2, 22, 25, 3, 31
etc. Is this a known bug?

Is there a way to do an exact match but only on some columns?

**Comment by myspace-nu** [comment]
> When I add this flag I still get numbers sorted as 1, 13, 14, 16, 2, 22, 25, 3, 31 etc. Is this a known bug?

There is no known bug. Please provide (or link to) an example if you feel something is not working as intended. Check out the last table codepen for a working example.
https://codepen.io/myspace-nu/pen/ZVEKyR

> Is there a way to do an exact match but only on some columns?

No. But you can hook up your own sort logic to the sortFunction setting to perform any magic you'd like.
