### ISSUE TITLE
sortOrder not working

### ISSUE THREAD

**Issue by xuefeng-huang** [myspace-nu/jquery.fancyTable#4]
I would like to sort my table column in reverse order, but it does not work. The setting I used for initialise fancyTable is 
  ```
$("#sampleTableA").fancyTable({
    sortColumn: 1,
    sortOrder: -1 });
```
What have I done wrong?

**Comment by myspace-nu** [comment]
sortOrder is not a valid configuration option. However, it is a nice feature and I will add it to the next release.
