### ISSUE TITLE
Inquiry on globalSearch parameter

### ISSUE THREAD

**Issue by rdimayuga** [myspace-nu/jquery.fancyTable#40]
Hi, 

I would like to use this plugin for my dataset. However I opted out for GlobalSearch and that makes all my columns to have a a separate search text box. Is there a way to input which table columns to have the search box? In this instance, I want to have the last column of the table to not have this search box as I'm only using the last column to provide "settings/options" for each row of my dataset.

**Comment by myspace-nu** [comment]
No sorry. There is no such option.
