### ISSUE TITLE
How do I properly minify?

### ISSUE THREAD

**Issue by Azmaeus** [myspace-nu/jquery.fancyTable#43]
I made changes to add data-sortas="datetime", and have confirmed they work if I import fancyTable.js with my changes. I then run grunt, which generates fancyTables.min.js, and I import that instead and my update no longer works.

**Comment by myspace-nu** [comment]
When you run grunt without any options it will first run [eslint](https://eslint.org/) to validate your code. If everything looks ok it will then run uglify to minify your code. These steps are defined in Gruntfile.js. However if validation fails according to the current eslint config the process will be stop. The output from eslint should give you a hint what you need to fix to make your code validate ok. If your code works for your usecase and you dont care about the validation errors you can always run `grunt uglify` which will just run the uglify process to generate your minified file and call it a day.
