### ISSUE TITLE
fancyTable() doesn't work on Chrome version 116

### ISSUE THREAD

**Issue by sanmait3** [myspace-nu/jquery.fancyTable#46]
Hi folks, 

I'm using fancyTable() for quite sometime, but somehow it broke recently for Chrome. I didn't face any issue on other browsers but it somehow doesn't work with Chrome anymore. Can you help fix this?

Thanks.

**Comment by myspace-nu** [comment]
It works well when I test it in the latest version of Chrome 116. If you check the demo at https://codepen.io/myspace-nu/full/ZVEKyR does it work for you? If so, please verify that you don't have other scripts on your page that might fail and break script execution.

**Comment by sanmait3** [comment]
We're seeing the following errors for the FancyTable() plugin: 
```
[Chrome/jQuery Uncaught RangeError: Maximum call stack size exceeded](https://stackoverflow.com/questions/7658775/chrome-jquery-uncaught-rangeerror-maximum-call-stack-size-exceeded)
```

**Comment by myspace-nu** [comment]
Please see this thread: https://github.com/myspace-nu/jquery.fancyTable/issues/31#issuecomment-1142334892
