### ISSUE TITLE
Exclude column from globalSearch

### ISSUE THREAD

**Issue by rickhaasteren** [myspace-nu/jquery.fancyTable#5]
Awesome piece of code!

Would be nice if there was a way to exclude one or more columns from the globalSearch option. I have a table with lots of different data, but with an Edit button in every TR.

Searching for Ed... now shows all records. It would be nice if that column could be excluded.

**Comment by myspace-nu** [comment]
Thank you! :)

Sounds like a useful feature that won't add a lot of code. I'll add the option _globalSearchExcludeColumn_ to the next release.
