### ISSUE TITLE
Custom sorting with attributes

### ISSUE THREAD

**Issue by DubDub2011** [myspace-nu/jquery.fancyTable#50]
Hi, would be really handy if you could populate `o.sortAs` with any custom attribute which is then accessible through the sort function, see below:
![image](https://github.com/myspace-nu/jquery.fancyTable/assets/94190301/8f86a40e-985a-4a4d-a28d-c804e64e6cc7)

Where you'd then have something like:
```
            $("table").fancyTable({
                sortFunction: function(a, b, o){
                    if(o.sortAs[o.sortColumn] == 'numeric'){
                        return((o.sortOrder>0) ? parseFloat(a)-parseFloat(b) : parseFloat(b)-parseFloat(a));
                    } else if (o.sortAs[o.sortColumn] == 'wage'){
                        return // wage comparison
                    } else if (o.sortAs[o.sortColumn] == 'transferValue'){
                        return // transferValue comparison
                    } else {
                        return // default sort
                    }
            }});
```

My use case is that my html table may be generated with any combination of columns in different orders, and some columns may be missing.

e.g. I may have different table headers on different runs depending on my input.

Name | Age | Rec
Age | Name | Wage | Transfer Value

**Comment by myspace-nu** [comment]
Thanks for the suggestion. I have reviewed and accepted the PR :)
