### ISSUE TITLE
Search input: Replace 'blur/change/keyup' events with single 'input' event?

### ISSUE THREAD

**Issue by koosvanderkolk** [myspace-nu/jquery.fancyTable#52]
Thanks for the great little module!

I noticed that the search <input> elements are bound to 3 events

`.bind('change paste keyup')`

This causes 2 updates per keyup, which might impact performance on large tables. 

Cannot it be replace by the 'input' event?

**Comment by myspace-nu** [comment]
Nope, it will only trigger once per keypress. 'change' (which is the event I guess you are refering to) will not trigger until you leave the input. The various event handlers are used to cover operations such as paste (by keyboard or mouse) and (cut/delete) but mouse context menu events.
