### ISSUE TITLE
Search input: Add timeout to improve performance?

### ISSUE THREAD

**Issue by koosvanderkolk** [myspace-nu/jquery.fancyTable#53]
I noticed with large tables, performance is impacted while searching. This might partly be caused by the fact that each keyup triggers a complete table redraw.

This might be overcome by adding a small timeout

```
window.clearTimeout(inputTimeout);
let inputEl = this;
inputTimeout = window.setTimeout(function () {
  elm.fancyTable.search = $(inputEl).val();
  elm.fancyTable.page = 1;
  instance.tableUpdate(elm);
}, 200);
```

**Comment by myspace-nu** [comment]
Thanks for the feedback. I'll consider something like that for future versions.
