### ISSUE TITLE
keep search filter after reload/refresh page

### ISSUE THREAD

**Issue by floyk** [myspace-nu/jquery.fancyTable#55]
Hi,
I was trying to be able to keep the search filters after reload/refresh the page. do you have any idea how to do this ?

**Comment by myspace-nu** [comment]
There is no built-in support for this. But it is fairly easy to implement using the onInit function:
```
$("#someTable").fancyTable({
	onInit: (elm) => {
		$(elm).find("input").eq(0).val('some value');
		$(elm).find("input").eq(0).trigger('keyup');
	}
});
```
And then you can use [beforeunload](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) event to store the current value in the [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage)
