### ISSUE TITLE
Exclude column from being sortable

### ISSUE THREAD

**Issue by l33tpr0digy** [myspace-nu/jquery.fancyTable#56]
Hello. I am utilizing this plugin to display a list of products. I am working on adding the ability to bulk edit by having the first column be checkboxes so that the user can select multiple items on which to perform the bulk edit. I have all that working flawlessly except in my <thead> for that column, I have a "select all" checkbox but it gets a sortable link applied to it so instead of the user being able to check that box to select all, it just sorts that column 0. I was hoping there was a "sortas" = none or similar but didn't see one. I figured out how to prevent the sort link from being applied but in turn, it breaks the column sort (ie: clicking the header for column 2 causes FancyTable to sort column 1). How can I exclude a column from having the sorting link applied to the header but everything still function normally? Thanks!

**Comment by myspace-nu** [comment]
Around line [#220](https://github.com/myspace-nu/jquery.fancyTable/blob/master/src/fancyTable.js#L220), add this line:
```
elm.fancyTable.sortAs.push($(this).data('sortas'));
if($(this).data('sortas') == 'none'){ nAElm++; return } // Add this line
var content = $(this).html();
```
Then you can add `data-sortas="none"` to your `<th ...>`

**Comment by l33tpr0digy** [comment]
That worked! Thank you for the quick reply!
