### ISSUE TITLE
Pagination buttons on top of table

### ISSUE THREAD

**Issue by stafra00** [myspace-nu/jquery.fancyTable#60]
Hi,
Very nice script!
How can you place the pagination buttons on top of the table in stead of below?

Thank you,

Kind regards,

**Comment by myspace-nu** [comment]
Please refer to the [README](https://github.com/myspace-nu/jquery.fancyTable/blob/master/README.md) and the option `paginationElement` which allows you to specify an element where the pagination control shoule be placed.
