### ISSUE TITLE
Table with row numbers

### ISSUE THREAD

**Issue by altan5** [myspace-nu/jquery.fancyTable#61]
Is it possible to make a column with the row numbers, so that when sorting by other columns, the row numbers always remain in the order 1, 2, 3...
Thanks!

**Comment by myspace-nu** [comment]
There is no build in funtionality for that (it seems like an edge case), but it's easily accomplished using the onUpdate event:

```
onUpdate: (elm) =>{
	let i=1;
	[...elm.querySelectorAll("tr td:first-child")].forEach(el => {
		el.innerHTML=i++;
	});
}
```
Replace td:first-child with [:nth-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) if you want to use anything else than the first column.
