### ISSUE TITLE
destroy instance

### ISSUE THREAD

**Issue by petitmamouth** [myspace-nu/jquery.fancyTable#7]
Hi, 
I'm still using FancyTable.min.js for the first time tonight.
I have a single table.
The thead is define in the php files.
The row are still display with a  js function (json file of an ajax)
I have add the definition of fancy after drawing my table.
It works...
But, when i refresh the table, the fancy draw another search toolbar....
On the screen captures, your see that the script add each time i refresh the php file another search toolbar.

How to detroy the current instance before reloading ?

Function drawTable() {

// here the Ajax function genrate a string call tbl
//Append the tbl string to draw the table
			$("#TBReg").append(tbl);

// Add Fancy
			$("#makeEditable").fancyTable({
			  sortColumn:1, // column number for initial sorting
			  sortOrder: 'descending', // 'desc', 'descending', 'asc', 'ascending', -1 (descending) and 1 (ascending)
			  sortable: true,
			  pagination: true, // default: false
			  searchable: true,
			  globalSearch: true,
			  // globalSearchExcludeColumns: [2,5] // exclude column 2 & 5
			});
![firts_loading](https://user-images.githubusercontent.com/47393109/68331877-0e3b7380-00d6-11ea-9932-a24dc3597ef6.PNG)
![second_refresh_one_time](https://user-images.githubusercontent.com/47393109/68331878-0e3b7380-00d6-11ea-8cfc-45f0b7a52959.PNG)
![third_refresh_another_time](https://user-images.githubusercontent.com/47393109/68331879-0e3b7380-00d6-11ea-8cef-421a0e1bebd0.PNG)

}

Best regards

**Comment by myspace-nu** [comment]
I have added a reinit method that you can use to reinitialize a fancyTable once new rows has been added to the `<tbody>`. See [Codepen](https://codepen.io/myspace-nu/full/ZVEKyR) for example.
