### ISSUE TITLE
order by number size

### ISSUE THREAD

**Issue by love010608** [myspace-nu/jquery.fancyTable#9]
I want to sort by number size. How can I do?exaple I want to sort ::2 5 10 25 .but the frame will:10 2 25 5

**Comment by myspace-nu** [comment]
You can use data-sortas="numeric" in the table header for the column in question.
```
<table>
   <thead>
      <tr>
         <th data-sortas="numeric">Miles</td>
...
```

**Comment by love010608** [comment]
it's work.thank U

**Comment by love010608** [comment]
I have a new question.If  data-sortas="numeric" ,how can I filter an area?Exaple 15,25,8,63,7,9,13.I want chose the number>10,the result 15,25,63,13.

**Comment by fitmos** [comment]
It works well, many thanks
